package com.albertominetti.orderbook.engine;

import com.albertominetti.orderbook.domain.OrderView;
import com.albertominetti.orderbook.domain.Trade;

import java.util.List;

/**
 * Outcome of submitting an order to the matching engine.
 *
 * @param order  the submitted order, with its final status and remaining quantity
 * @param trades the trades generated by this submission, in execution order
 */
public record MatchResult(OrderView order, List<Trade> trades) {

    public MatchResult {
        trades = List.copyOf(trades);
    }
}
