package com.albertominetti.orderbook.dto;

import com.albertominetti.orderbook.engine.MatchResult;

import java.util.List;

/**
 * Response of {@code POST /api/orders}: the accepted order in its final state
 * plus every trade it generated, in execution order.
 *
 * @param order  the submitted order after matching
 * @param trades trades generated by this submission
 */
public record MatchResponse(OrderResponse order, List<TradeResponse> trades) {

    public static MatchResponse from(MatchResult result) {
        return new MatchResponse(
                OrderResponse.from(result.order()),
                result.trades().stream().map(TradeResponse::from).toList());
    }
}
