package com.albertominetti.orderbook.service;

import com.albertominetti.orderbook.domain.InstrumentRef;
import java.util.List;

/**
 * Instrument catalogue baked into the code, so it is always available at runtime, including
 * inside a GraalVM native image where a classpath resource would have to be hinted explicitly.
 */
final class InstrumentCatalogData {

    private InstrumentCatalogData() {
    }

    static final List<InstrumentRef> ALL = List.of(
            new InstrumentRef("UBSG", "UBS Group", "SIX"),
            new InstrumentRef("CSGN", "Credit Suisse Group", "SIX"),
            new InstrumentRef("BAER", "Julius B\u00e4r Gruppe", "SIX"),
            new InstrumentRef("SREN", "Swiss Re", "SIX"),
            new InstrumentRef("NESN", "Nestl\u00e9", "SIX"),
            new InstrumentRef("ROG", "Roche Holding", "SIX"),
            new InstrumentRef("NOVN", "Novartis", "SIX"),
            new InstrumentRef("ZURN", "Zurich Insurance Group", "SIX"),
            new InstrumentRef("ABBN", "ABB", "SIX"),
            new InstrumentRef("GIVN", "Givaudan", "SIX"),
            new InstrumentRef("LONN", "Lonza Group", "SIX"),
            new InstrumentRef("SIKA", "Sika", "SIX"),
            new InstrumentRef("HOLN", "Holcim", "SIX"),
            new InstrumentRef("SCMN", "Swisscom", "SIX"),
            new InstrumentRef("ALC", "Alcon", "SIX"),
            new InstrumentRef("CFR", "Compagnie Financi\u00e8re Richemont", "SIX"),
            new InstrumentRef("UHR", "Swatch Group", "SIX"),
            new InstrumentRef("SOON", "Sonova Holding", "SIX"),
            new InstrumentRef("ADEN", "Adecco Group", "SIX"),
            new InstrumentRef("GEBN", "Geberit", "SIX"),
            new InstrumentRef("SGSN", "SGS", "SIX"),
            new InstrumentRef("PGHN", "Partners Group Holding", "SIX"),
            new InstrumentRef("KNIN", "Kuehne + Nagel International", "SIX"),
            new InstrumentRef("SLHN", "Swiss Life Holding", "SIX"),
            new InstrumentRef("BALN", "B\u00e2loise Holding", "SIX"),
            new InstrumentRef("HELN", "Helvetia Holding", "SIX"),
            new InstrumentRef("EMSN", "EMS-CHEMIE Holding", "SIX"),
            new InstrumentRef("STMN", "Straumann Holding", "SIX"),
            new InstrumentRef("LOGN", "Logitech International", "SIX"),
            new InstrumentRef("BARN", "Barry Callebaut", "SIX"),
            new InstrumentRef("LISN", "Lindt & Spr\u00fcngli", "SIX"),
            new InstrumentRef("SIGN", "SIG Group", "SIX"),
            new InstrumentRef("VACN", "VAT Group", "SIX"),
            new InstrumentRef("SFSN", "SFS Group", "SIX"),
            new InstrumentRef("AVOL", "Avolta", "SIX"),
            new InstrumentRef("BANB", "Bachem Holding", "SIX"),
            new InstrumentRef("TEMN", "Temenos", "SIX"),
            new InstrumentRef("CLN", "Clariant", "SIX"),
            new InstrumentRef("DOKA", "Dormakaba Holding", "SIX"),
            new InstrumentRef("SUN", "Sulzer", "SIX"),
            new InstrumentRef("IMPN", "Implenia", "SIX"),
            new InstrumentRef("SPSN", "Swiss Prime Site", "SIX"),
            new InstrumentRef("PSPN", "PSP Swiss Property", "SIX"),
            new InstrumentRef("BCVN", "BC Vaudoise", "SIX"),
            new InstrumentRef("CMBN", "Cembra Money Bank", "SIX"),
            new InstrumentRef("GALE", "Galenica", "SIX"),
            new InstrumentRef("VZN", "VZ Holding", "SIX"),
            new InstrumentRef("A", "Agilent Technologies", "S&P 500"),
            new InstrumentRef("AAPL", "Apple Inc.", "S&P 500"),
            new InstrumentRef("ABBV", "AbbVie", "S&P 500"),
            new InstrumentRef("ABNB", "Airbnb", "S&P 500"),
            new InstrumentRef("ABT", "Abbott Laboratories", "S&P 500"),
            new InstrumentRef("ACGL", "Arch Capital Group", "S&P 500"),
            new InstrumentRef("ACN", "Accenture", "S&P 500"),
            new InstrumentRef("ADBE", "Adobe Inc.", "S&P 500"),
            new InstrumentRef("ADI", "Analog Devices", "S&P 500"),
            new InstrumentRef("ADM", "Archer Daniels Midland", "S&P 500"),
            new InstrumentRef("ADP", "Automatic Data Processing", "S&P 500"),
            new InstrumentRef("ADSK", "Autodesk", "S&P 500"),
            new InstrumentRef("AEE", "Ameren", "S&P 500"),
            new InstrumentRef("AEP", "American Electric Power", "S&P 500"),
            new InstrumentRef("AES", "AES Corporation", "S&P 500"),
            new InstrumentRef("AFL", "Aflac", "S&P 500"),
            new InstrumentRef("AIG", "American International Group", "S&P 500"),
            new InstrumentRef("AIZ", "Assurant", "S&P 500"),
            new InstrumentRef("AJG", "Arthur J. Gallagher & Co.", "S&P 500"),
            new InstrumentRef("AKAM", "Akamai Technologies", "S&P 500"),
            new InstrumentRef("ALB", "Albemarle Corporation", "S&P 500"),
            new InstrumentRef("ALGN", "Align Technology", "S&P 500"),
            new InstrumentRef("ALL", "Allstate", "S&P 500"),
            new InstrumentRef("ALLE", "Allegion", "S&P 500"),
            new InstrumentRef("AMAT", "Applied Materials", "S&P 500"),
            new InstrumentRef("AMCR", "Amcor", "S&P 500"),
            new InstrumentRef("AMD", "Advanced Micro Devices", "S&P 500"),
            new InstrumentRef("AME", "Ametek", "S&P 500"),
            new InstrumentRef("AMGN", "Amgen", "S&P 500"),
            new InstrumentRef("AMP", "Ameriprise Financial", "S&P 500"),
            new InstrumentRef("AMT", "American Tower", "S&P 500"),
            new InstrumentRef("AMZN", "Amazon", "S&P 500"),
            new InstrumentRef("ANET", "Arista Networks", "S&P 500"),
            new InstrumentRef("AON", "Aon plc", "S&P 500"),
            new InstrumentRef("AOS", "A. O. Smith", "S&P 500"),
            new InstrumentRef("APA", "APA Corporation", "S&P 500"),
            new InstrumentRef("APD", "Air Products", "S&P 500"),
            new InstrumentRef("APH", "Amphenol", "S&P 500"),
            new InstrumentRef("APO", "Apollo Global Management", "S&P 500"),
            new InstrumentRef("APP", "AppLovin", "S&P 500"),
            new InstrumentRef("APTV", "Aptiv", "S&P 500"),
            new InstrumentRef("ARE", "Alexandria Real Estate Equities", "S&P 500"),
            new InstrumentRef("ARES", "Ares Management", "S&P 500"),
            new InstrumentRef("ATO", "Atmos Energy", "S&P 500"),
            new InstrumentRef("AVGO", "Broadcom", "S&P 500"),
            new InstrumentRef("AVY", "Avery Dennison", "S&P 500"),
            new InstrumentRef("AWK", "American Water Works", "S&P 500"),
            new InstrumentRef("AXON", "Axon Enterprise", "S&P 500"),
            new InstrumentRef("AXP", "American Express", "S&P 500"),
            new InstrumentRef("AZO", "AutoZone", "S&P 500"),
            new InstrumentRef("BA", "Boeing", "S&P 500"),
            new InstrumentRef("BAC", "Bank of America", "S&P 500"),
            new InstrumentRef("BALL", "Ball Corporation", "S&P 500"),
            new InstrumentRef("BAX", "Baxter International", "S&P 500"),
            new InstrumentRef("BBY", "Best Buy", "S&P 500"),
            new InstrumentRef("BDX", "Becton Dickinson", "S&P 500"),
            new InstrumentRef("BE", "Bloom Energy", "S&P 500"),
            new InstrumentRef("BEN", "Franklin Resources", "S&P 500"),
            new InstrumentRef("BF.B", "Brown\u2013Forman", "S&P 500"),
            new InstrumentRef("BG", "Bunge Global", "S&P 500"),
            new InstrumentRef("BIIB", "Biogen", "S&P 500"),
            new InstrumentRef("BKNG", "Booking Holdings", "S&P 500"),
            new InstrumentRef("BKR", "Baker Hughes", "S&P 500"),
            new InstrumentRef("BLK", "BlackRock", "S&P 500"),
            new InstrumentRef("BMY", "Bristol Myers Squibb", "S&P 500"),
            new InstrumentRef("BNY", "BNY Mellon", "S&P 500"),
            new InstrumentRef("BR", "Broadridge Financial Solutions", "S&P 500"),
            new InstrumentRef("BRK.B", "Berkshire Hathaway", "S&P 500"),
            new InstrumentRef("BRO", "Brown & Brown", "S&P 500"),
            new InstrumentRef("BSX", "Boston Scientific", "S&P 500"),
            new InstrumentRef("BX", "Blackstone Inc.", "S&P 500"),
            new InstrumentRef("BXP", "BXP, Inc.", "S&P 500"),
            new InstrumentRef("C", "Citigroup", "S&P 500"),
            new InstrumentRef("CAH", "Cardinal Health", "S&P 500"),
            new InstrumentRef("CARR", "Carrier Global", "S&P 500"),
            new InstrumentRef("CASY", "Casey's", "S&P 500"),
            new InstrumentRef("CAT", "Caterpillar Inc.", "S&P 500"),
            new InstrumentRef("CB", "Chubb Limited", "S&P 500"),
            new InstrumentRef("CBOE", "Cboe Global Markets", "S&P 500"),
            new InstrumentRef("CBRE", "CBRE Group", "S&P 500"),
            new InstrumentRef("CCI", "Crown Castle", "S&P 500"),
            new InstrumentRef("CCL", "Carnival Corporation", "S&P 500"),
            new InstrumentRef("CDNS", "Cadence Design Systems", "S&P 500"),
            new InstrumentRef("CDW", "CDW Corporation", "S&P 500"),
            new InstrumentRef("CEG", "Constellation Energy", "S&P 500"),
            new InstrumentRef("CF", "CF Industries", "S&P 500"),
            new InstrumentRef("CFG", "Citizens Financial Group", "S&P 500"),
            new InstrumentRef("CHD", "Church & Dwight", "S&P 500"),
            new InstrumentRef("CHRW", "C.H. Robinson", "S&P 500"),
            new InstrumentRef("CHTR", "Charter Communications", "S&P 500"),
            new InstrumentRef("CI", "Cigna", "S&P 500"),
            new InstrumentRef("CIEN", "Ciena", "S&P 500"),
            new InstrumentRef("CINF", "Cincinnati Financial", "S&P 500"),
            new InstrumentRef("CL", "Colgate-Palmolive", "S&P 500"),
            new InstrumentRef("CLX", "Clorox", "S&P 500"),
            new InstrumentRef("CMCSA", "Comcast", "S&P 500"),
            new InstrumentRef("CME", "CME Group", "S&P 500"),
            new InstrumentRef("CMG", "Chipotle Mexican Grill", "S&P 500"),
            new InstrumentRef("CMI", "Cummins", "S&P 500"),
            new InstrumentRef("CMS", "CMS Energy", "S&P 500"),
            new InstrumentRef("CNC", "Centene Corporation", "S&P 500"),
            new InstrumentRef("CNP", "CenterPoint Energy", "S&P 500"),
            new InstrumentRef("COF", "Capital One", "S&P 500"),
            new InstrumentRef("COHR", "Coherent Corp.", "S&P 500"),
            new InstrumentRef("COIN", "Coinbase", "S&P 500"),
            new InstrumentRef("COO", "Cooper Companies (The)", "S&P 500"),
            new InstrumentRef("COP", "ConocoPhillips", "S&P 500"),
            new InstrumentRef("COR", "Cencora", "S&P 500"),
            new InstrumentRef("COST", "Costco", "S&P 500"),
            new InstrumentRef("CPAY", "Corpay", "S&P 500"),
            new InstrumentRef("CPRT", "Copart", "S&P 500"),
            new InstrumentRef("CPT", "Camden Property Trust", "S&P 500"),
            new InstrumentRef("CRH", "CRH plc", "S&P 500"),
            new InstrumentRef("CRL", "Charles River Laboratories", "S&P 500"),
            new InstrumentRef("CRM", "Salesforce", "S&P 500"),
            new InstrumentRef("CRWD", "CrowdStrike", "S&P 500"),
            new InstrumentRef("CSCO", "Cisco", "S&P 500"),
            new InstrumentRef("CSGP", "CoStar Group", "S&P 500"),
            new InstrumentRef("CSX", "CSX Corporation", "S&P 500"),
            new InstrumentRef("CTAS", "Cintas", "S&P 500"),
            new InstrumentRef("CTSH", "Cognizant", "S&P 500"),
            new InstrumentRef("CTVA", "Corteva", "S&P 500"),
            new InstrumentRef("CVNA", "Carvana", "S&P 500"),
            new InstrumentRef("CVS", "CVS Health", "S&P 500"),
            new InstrumentRef("CVX", "Chevron Corporation", "S&P 500"),
            new InstrumentRef("D", "Dominion Energy", "S&P 500"),
            new InstrumentRef("DAL", "Delta Air Lines", "S&P 500"),
            new InstrumentRef("DASH", "DoorDash", "S&P 500"),
            new InstrumentRef("DD", "DuPont", "S&P 500"),
            new InstrumentRef("DDOG", "Datadog", "S&P 500"),
            new InstrumentRef("DE", "Deere & Company", "S&P 500"),
            new InstrumentRef("DECK", "Deckers Brands", "S&P 500"),
            new InstrumentRef("DELL", "Dell Technologies", "S&P 500"),
            new InstrumentRef("DG", "Dollar General", "S&P 500"),
            new InstrumentRef("DGX", "Quest Diagnostics", "S&P 500"),
            new InstrumentRef("DHI", "D. R. Horton", "S&P 500"),
            new InstrumentRef("DHR", "Danaher Corporation", "S&P 500"),
            new InstrumentRef("DIS", "Walt Disney Company (The)", "S&P 500"),
            new InstrumentRef("DLR", "Digital Realty", "S&P 500"),
            new InstrumentRef("DLTR", "Dollar Tree", "S&P 500"),
            new InstrumentRef("DOC", "Healthpeak Properties", "S&P 500"),
            new InstrumentRef("DOV", "Dover Corporation", "S&P 500"),
            new InstrumentRef("DOW", "Dow Inc.", "S&P 500"),
            new InstrumentRef("DPZ", "Domino's", "S&P 500"),
            new InstrumentRef("DRI", "Darden Restaurants", "S&P 500"),
            new InstrumentRef("DTE", "DTE Energy", "S&P 500"),
            new InstrumentRef("DUK", "Duke Energy", "S&P 500"),
            new InstrumentRef("DVA", "DaVita", "S&P 500"),
            new InstrumentRef("DVN", "Devon Energy", "S&P 500"),
            new InstrumentRef("DXCM", "Dexcom", "S&P 500"),
            new InstrumentRef("EBAY", "eBay Inc.", "S&P 500"),
            new InstrumentRef("ECHO", "EchoStar", "S&P 500"),
            new InstrumentRef("ECL", "Ecolab", "S&P 500"),
            new InstrumentRef("ED", "Consolidated Edison", "S&P 500"),
            new InstrumentRef("EFX", "Equifax", "S&P 500"),
            new InstrumentRef("EG", "Everest Group", "S&P 500"),
            new InstrumentRef("EIX", "Edison International", "S&P 500"),
            new InstrumentRef("EL", "Est\u00e9e Lauder Companies (The)", "S&P 500"),
            new InstrumentRef("ELV", "Elevance Health", "S&P 500"),
            new InstrumentRef("EME", "Emcor", "S&P 500"),
            new InstrumentRef("EMR", "Emerson Electric", "S&P 500"),
            new InstrumentRef("EOG", "EOG Resources", "S&P 500"),
            new InstrumentRef("EQIX", "Equinix", "S&P 500"),
            new InstrumentRef("EQT", "EQT Corporation", "S&P 500"),
            new InstrumentRef("ERIE", "Erie Indemnity", "S&P 500"),
            new InstrumentRef("ES", "Eversource Energy", "S&P 500"),
            new InstrumentRef("ESS", "Essex Property Trust", "S&P 500"),
            new InstrumentRef("ETN", "Eaton Corporation", "S&P 500"),
            new InstrumentRef("ETR", "Entergy", "S&P 500"),
            new InstrumentRef("EVRG", "Evergy", "S&P 500"),
            new InstrumentRef("EW", "Edwards Lifesciences", "S&P 500"),
            new InstrumentRef("EXC", "Exelon", "S&P 500"),
            new InstrumentRef("EXE", "Expand Energy", "S&P 500"),
            new InstrumentRef("EXPD", "Expeditors International", "S&P 500"),
            new InstrumentRef("EXPE", "Expedia Group", "S&P 500"),
            new InstrumentRef("EXR", "Extra Space Storage", "S&P 500"),
            new InstrumentRef("F", "Ford Motor Company", "S&P 500"),
            new InstrumentRef("FANG", "Diamondback Energy", "S&P 500"),
            new InstrumentRef("FAST", "Fastenal", "S&P 500"),
            new InstrumentRef("FCX", "Freeport-McMoRan", "S&P 500"),
            new InstrumentRef("FDS", "FactSet", "S&P 500"),
            new InstrumentRef("FDX", "FedEx", "S&P 500"),
            new InstrumentRef("FDXF", "FedEx Freight", "S&P 500"),
            new InstrumentRef("FE", "FirstEnergy", "S&P 500"),
            new InstrumentRef("FERG", "Ferguson Enterprises", "S&P 500"),
            new InstrumentRef("FFIV", "F5, Inc.", "S&P 500"),
            new InstrumentRef("FICO", "Fair Isaac", "S&P 500"),
            new InstrumentRef("FIS", "Fidelity National Information Services", "S&P 500"),
            new InstrumentRef("FISV", "Fiserv", "S&P 500"),
            new InstrumentRef("FITB", "Fifth Third Bancorp", "S&P 500"),
            new InstrumentRef("FIX", "Comfort Systems USA", "S&P 500"),
            new InstrumentRef("FLEX", "Flex Ltd.", "S&P 500"),
            new InstrumentRef("FOX", "Fox Corporation (Class B)", "S&P 500"),
            new InstrumentRef("FOXA", "Fox Corporation (Class A)", "S&P 500"),
            new InstrumentRef("FRT", "Federal Realty Investment Trust", "S&P 500"),
            new InstrumentRef("FSLR", "First Solar", "S&P 500"),
            new InstrumentRef("FTNT", "Fortinet", "S&P 500"),
            new InstrumentRef("FTV", "Fortive", "S&P 500"),
            new InstrumentRef("GD", "General Dynamics", "S&P 500"),
            new InstrumentRef("GDDY", "GoDaddy", "S&P 500"),
            new InstrumentRef("GE", "GE Aerospace", "S&P 500"),
            new InstrumentRef("GEHC", "GE HealthCare", "S&P 500"),
            new InstrumentRef("GEN", "Gen Digital", "S&P 500"),
            new InstrumentRef("GEV", "GE Vernova", "S&P 500"),
            new InstrumentRef("GILD", "Gilead Sciences", "S&P 500"),
            new InstrumentRef("GIS", "General Mills", "S&P 500"),
            new InstrumentRef("GL", "Globe Life", "S&P 500"),
            new InstrumentRef("GLW", "Corning Inc.", "S&P 500"),
            new InstrumentRef("GM", "General Motors", "S&P 500"),
            new InstrumentRef("GNRC", "Generac", "S&P 500"),
            new InstrumentRef("GOOG", "Alphabet Inc. (Class C)", "S&P 500"),
            new InstrumentRef("GOOGL", "Alphabet Inc. (Class A)", "S&P 500"),
            new InstrumentRef("GPC", "Genuine Parts Company", "S&P 500"),
            new InstrumentRef("GPN", "Global Payments", "S&P 500"),
            new InstrumentRef("GRMN", "Garmin", "S&P 500"),
            new InstrumentRef("GS", "Goldman Sachs", "S&P 500"),
            new InstrumentRef("GWW", "W. W. Grainger", "S&P 500"),
            new InstrumentRef("HAL", "Halliburton", "S&P 500"),
            new InstrumentRef("HAS", "Hasbro", "S&P 500"),
            new InstrumentRef("HBAN", "Huntington Bancshares", "S&P 500"),
            new InstrumentRef("HCA", "HCA Healthcare", "S&P 500"),
            new InstrumentRef("HD", "Home Depot (The)", "S&P 500"),
            new InstrumentRef("HIG", "Hartford (The)", "S&P 500"),
            new InstrumentRef("HII", "Huntington Ingalls Industries", "S&P 500"),
            new InstrumentRef("HLT", "Hilton Worldwide", "S&P 500"),
            new InstrumentRef("HON", "Honeywell Technologies", "S&P 500"),
            new InstrumentRef("HONA", "Honeywell Aerospace", "S&P 500"),
            new InstrumentRef("HOOD", "Robinhood Markets", "S&P 500"),
            new InstrumentRef("HPE", "Hewlett Packard Enterprise", "S&P 500"),
            new InstrumentRef("HPQ", "HP Inc.", "S&P 500"),
            new InstrumentRef("HRL", "Hormel Foods", "S&P 500"),
            new InstrumentRef("HSIC", "Henry Schein", "S&P 500"),
            new InstrumentRef("HST", "Host Hotels & Resorts", "S&P 500"),
            new InstrumentRef("HSY", "Hershey Company (The)", "S&P 500"),
            new InstrumentRef("HUBB", "Hubbell Incorporated", "S&P 500"),
            new InstrumentRef("HUM", "Humana", "S&P 500"),
            new InstrumentRef("HWM", "Howmet Aerospace", "S&P 500"),
            new InstrumentRef("IBKR", "Interactive Brokers", "S&P 500"),
            new InstrumentRef("IBM", "IBM", "S&P 500"),
            new InstrumentRef("ICE", "Intercontinental Exchange", "S&P 500"),
            new InstrumentRef("IDXX", "Idexx Laboratories", "S&P 500"),
            new InstrumentRef("IEX", "IDEX Corporation", "S&P 500"),
            new InstrumentRef("IFF", "International Flavors & Fragrances", "S&P 500"),
            new InstrumentRef("ILMN", "Illumina, Inc.", "S&P 500"),
            new InstrumentRef("INCY", "Incyte", "S&P 500"),
            new InstrumentRef("INTC", "Intel", "S&P 500"),
            new InstrumentRef("INTU", "Intuit", "S&P 500"),
            new InstrumentRef("INVH", "Invitation Homes", "S&P 500"),
            new InstrumentRef("IP", "International Paper", "S&P 500"),
            new InstrumentRef("IQV", "IQVIA", "S&P 500"),
            new InstrumentRef("IR", "Ingersoll Rand", "S&P 500"),
            new InstrumentRef("IRM", "Iron Mountain", "S&P 500"),
            new InstrumentRef("ISRG", "Intuitive Surgical", "S&P 500"),
            new InstrumentRef("IT", "Gartner", "S&P 500"),
            new InstrumentRef("ITW", "Illinois Tool Works", "S&P 500"),
            new InstrumentRef("IVZ", "Invesco", "S&P 500"),
            new InstrumentRef("J", "Jacobs Solutions", "S&P 500"),
            new InstrumentRef("JBHT", "J.B. Hunt", "S&P 500"),
            new InstrumentRef("JBL", "Jabil", "S&P 500"),
            new InstrumentRef("JCI", "Johnson Controls", "S&P 500"),
            new InstrumentRef("JKHY", "Jack Henry & Associates", "S&P 500"),
            new InstrumentRef("JNJ", "Johnson & Johnson", "S&P 500"),
            new InstrumentRef("JPM", "JPMorgan Chase", "S&P 500"),
            new InstrumentRef("KDP", "Keurig Dr Pepper", "S&P 500"),
            new InstrumentRef("KEY", "KeyCorp", "S&P 500"),
            new InstrumentRef("KEYS", "Keysight Technologies", "S&P 500"),
            new InstrumentRef("KHC", "Kraft Heinz", "S&P 500"),
            new InstrumentRef("KIM", "Kimco Realty", "S&P 500"),
            new InstrumentRef("KKR", "KKR & Co.", "S&P 500"),
            new InstrumentRef("KLAC", "KLA Corporation", "S&P 500"),
            new InstrumentRef("KMB", "Kimberly-Clark", "S&P 500"),
            new InstrumentRef("KMI", "Kinder Morgan", "S&P 500"),
            new InstrumentRef("KO", "Coca-Cola Company (The)", "S&P 500"),
            new InstrumentRef("KR", "Kroger", "S&P 500"),
            new InstrumentRef("KVUE", "Kenvue", "S&P 500"),
            new InstrumentRef("L", "Loews Corporation", "S&P 500"),
            new InstrumentRef("LDOS", "Leidos", "S&P 500"),
            new InstrumentRef("LEN", "Lennar", "S&P 500"),
            new InstrumentRef("LH", "Labcorp", "S&P 500"),
            new InstrumentRef("LHX", "L3Harris", "S&P 500"),
            new InstrumentRef("LII", "Lennox International", "S&P 500"),
            new InstrumentRef("LIN", "Linde plc", "S&P 500"),
            new InstrumentRef("LITE", "Lumentum", "S&P 500"),
            new InstrumentRef("LLY", "Lilly (Eli)", "S&P 500"),
            new InstrumentRef("LMT", "Lockheed Martin", "S&P 500"),
            new InstrumentRef("LNT", "Alliant Energy", "S&P 500"),
            new InstrumentRef("LOW", "Lowe's", "S&P 500"),
            new InstrumentRef("LRCX", "Lam Research", "S&P 500"),
            new InstrumentRef("LULU", "Lululemon Athletica", "S&P 500"),
            new InstrumentRef("LUV", "Southwest Airlines", "S&P 500"),
            new InstrumentRef("LVS", "Las Vegas Sands", "S&P 500"),
            new InstrumentRef("LYB", "LyondellBasell", "S&P 500"),
            new InstrumentRef("LYV", "Live Nation Entertainment", "S&P 500"),
            new InstrumentRef("MA", "Mastercard", "S&P 500"),
            new InstrumentRef("MAA", "Mid-America Apartment Communities", "S&P 500"),
            new InstrumentRef("MAR", "Marriott International", "S&P 500"),
            new InstrumentRef("MAS", "Masco", "S&P 500"),
            new InstrumentRef("MCD", "McDonald's", "S&P 500"),
            new InstrumentRef("MCHP", "Microchip Technology", "S&P 500"),
            new InstrumentRef("MCK", "McKesson Corporation", "S&P 500"),
            new InstrumentRef("MCO", "Moody's Corporation", "S&P 500"),
            new InstrumentRef("MDLZ", "Mondelez International", "S&P 500"),
            new InstrumentRef("MDT", "Medtronic", "S&P 500"),
            new InstrumentRef("MET", "MetLife", "S&P 500"),
            new InstrumentRef("META", "Meta Platforms", "S&P 500"),
            new InstrumentRef("MGM", "MGM Resorts", "S&P 500"),
            new InstrumentRef("MKC", "McCormick & Company", "S&P 500"),
            new InstrumentRef("MLM", "Martin Marietta Materials", "S&P 500"),
            new InstrumentRef("MMM", "3M", "S&P 500"),
            new InstrumentRef("MNST", "Monster Beverage", "S&P 500"),
            new InstrumentRef("MO", "Altria", "S&P 500"),
            new InstrumentRef("MOS", "Mosaic Company (The)", "S&P 500"),
            new InstrumentRef("MPC", "Marathon Petroleum", "S&P 500"),
            new InstrumentRef("MPWR", "Monolithic Power Systems", "S&P 500"),
            new InstrumentRef("MRK", "Merck & Co.", "S&P 500"),
            new InstrumentRef("MRNA", "Moderna", "S&P 500"),
            new InstrumentRef("MRSH", "Marsh McLennan", "S&P 500"),
            new InstrumentRef("MRVL", "Marvell Technology", "S&P 500"),
            new InstrumentRef("MS", "Morgan Stanley", "S&P 500"),
            new InstrumentRef("MSCI", "MSCI", "S&P 500"),
            new InstrumentRef("MSFT", "Microsoft", "S&P 500"),
            new InstrumentRef("MSI", "Motorola Solutions", "S&P 500"),
            new InstrumentRef("MTB", "M&T Bank", "S&P 500"),
            new InstrumentRef("MTD", "Mettler Toledo", "S&P 500"),
            new InstrumentRef("MU", "Micron Technology", "S&P 500"),
            new InstrumentRef("NCLH", "Norwegian Cruise Line Holdings", "S&P 500"),
            new InstrumentRef("NDAQ", "Nasdaq, Inc.", "S&P 500"),
            new InstrumentRef("NDSN", "Nordson Corporation", "S&P 500"),
            new InstrumentRef("NEE", "NextEra Energy", "S&P 500"),
            new InstrumentRef("NEM", "Newmont", "S&P 500"),
            new InstrumentRef("NFLX", "Netflix", "S&P 500"),
            new InstrumentRef("NI", "NiSource", "S&P 500"),
            new InstrumentRef("NKE", "Nike, Inc.", "S&P 500"),
            new InstrumentRef("NOC", "Northrop Grumman", "S&P 500"),
            new InstrumentRef("NOW", "ServiceNow", "S&P 500"),
            new InstrumentRef("NRG", "NRG Energy", "S&P 500"),
            new InstrumentRef("NSC", "Norfolk Southern", "S&P 500"),
            new InstrumentRef("NTAP", "NetApp", "S&P 500"),
            new InstrumentRef("NTRS", "Northern Trust", "S&P 500"),
            new InstrumentRef("NUE", "Nucor", "S&P 500"),
            new InstrumentRef("NVDA", "Nvidia", "S&P 500"),
            new InstrumentRef("NVR", "NVR, Inc.", "S&P 500"),
            new InstrumentRef("NWS", "News Corp (Class B)", "S&P 500"),
            new InstrumentRef("NWSA", "News Corp (Class A)", "S&P 500"),
            new InstrumentRef("NXPI", "NXP Semiconductors", "S&P 500"),
            new InstrumentRef("O", "Realty Income", "S&P 500"),
            new InstrumentRef("ODFL", "Old Dominion", "S&P 500"),
            new InstrumentRef("OKE", "Oneok", "S&P 500"),
            new InstrumentRef("OMC", "Omnicom Group", "S&P 500"),
            new InstrumentRef("ON", "ON Semiconductor", "S&P 500"),
            new InstrumentRef("ORCL", "Oracle Corporation", "S&P 500"),
            new InstrumentRef("ORLY", "O'Reilly Automotive", "S&P 500"),
            new InstrumentRef("OTIS", "Otis Worldwide", "S&P 500"),
            new InstrumentRef("OXY", "Occidental Petroleum", "S&P 500"),
            new InstrumentRef("P", "Everpure", "S&P 500"),
            new InstrumentRef("PANW", "Palo Alto Networks", "S&P 500"),
            new InstrumentRef("PAYX", "Paychex", "S&P 500"),
            new InstrumentRef("PCAR", "Paccar", "S&P 500"),
            new InstrumentRef("PCG", "PG&E Corporation", "S&P 500"),
            new InstrumentRef("PEG", "Public Service Enterprise Group", "S&P 500"),
            new InstrumentRef("PEP", "PepsiCo", "S&P 500"),
            new InstrumentRef("PFE", "Pfizer", "S&P 500"),
            new InstrumentRef("PFG", "Principal Financial Group", "S&P 500"),
            new InstrumentRef("PG", "Procter & Gamble", "S&P 500"),
            new InstrumentRef("PGR", "Progressive Corporation", "S&P 500"),
            new InstrumentRef("PH", "Parker Hannifin", "S&P 500"),
            new InstrumentRef("PHM", "PulteGroup", "S&P 500"),
            new InstrumentRef("PKG", "Packaging Corporation of America", "S&P 500"),
            new InstrumentRef("PLD", "Prologis", "S&P 500"),
            new InstrumentRef("PLTR", "Palantir Technologies", "S&P 500"),
            new InstrumentRef("PM", "Philip Morris International", "S&P 500"),
            new InstrumentRef("PNC", "PNC Financial Services", "S&P 500"),
            new InstrumentRef("PNR", "Pentair", "S&P 500"),
            new InstrumentRef("PNW", "Pinnacle West Capital", "S&P 500"),
            new InstrumentRef("PODD", "Insulet Corporation", "S&P 500"),
            new InstrumentRef("PPG", "PPG Industries", "S&P 500"),
            new InstrumentRef("PPL", "PPL Corporation", "S&P 500"),
            new InstrumentRef("PRU", "Prudential Financial", "S&P 500"),
            new InstrumentRef("PSA", "Public Storage", "S&P 500"),
            new InstrumentRef("PSKY", "Paramount Skydance Corporation", "S&P 500"),
            new InstrumentRef("PSX", "Phillips 66", "S&P 500"),
            new InstrumentRef("PTC", "PTC Inc.", "S&P 500"),
            new InstrumentRef("PWR", "Quanta Services", "S&P 500"),
            new InstrumentRef("PYPL", "PayPal", "S&P 500"),
            new InstrumentRef("Q", "Qnity Electronics", "S&P 500"),
            new InstrumentRef("QCOM", "Qualcomm", "S&P 500"),
            new InstrumentRef("RCL", "Royal Caribbean Group", "S&P 500"),
            new InstrumentRef("RDDT", "Reddit", "S&P 500"),
            new InstrumentRef("REG", "Regency Centers", "S&P 500"),
            new InstrumentRef("REGN", "Regeneron Pharmaceuticals", "S&P 500"),
            new InstrumentRef("RF", "Regions Financial Corporation", "S&P 500"),
            new InstrumentRef("RJF", "Raymond James Financial", "S&P 500"),
            new InstrumentRef("RL", "Ralph Lauren Corporation", "S&P 500"),
            new InstrumentRef("RMD", "ResMed|", "S&P 500"),
            new InstrumentRef("ROK", "Rockwell Automation", "S&P 500"),
            new InstrumentRef("ROL", "Rollins, Inc.", "S&P 500"),
            new InstrumentRef("ROP", "Roper Technologies", "S&P 500"),
            new InstrumentRef("ROST", "Ross Stores", "S&P 500"),
            new InstrumentRef("RSG", "Republic Services", "S&P 500"),
            new InstrumentRef("RTX", "RTX Corporation", "S&P 500"),
            new InstrumentRef("RVTY", "Revvity", "S&P 500"),
            new InstrumentRef("SBAC", "SBA Communications", "S&P 500"),
            new InstrumentRef("SBUX", "Starbucks", "S&P 500"),
            new InstrumentRef("SCHW", "Charles Schwab Corporation", "S&P 500"),
            new InstrumentRef("SHW", "Sherwin-Williams", "S&P 500"),
            new InstrumentRef("SJM", "J.M. Smucker Company (The)", "S&P 500"),
            new InstrumentRef("SLB", "Schlumberger", "S&P 500"),
            new InstrumentRef("SMCI", "Supermicro", "S&P 500"),
            new InstrumentRef("SNA", "Snap-on", "S&P 500"),
            new InstrumentRef("SNDK", "Sandisk", "S&P 500"),
            new InstrumentRef("SNPS", "Synopsys", "S&P 500"),
            new InstrumentRef("SO", "Southern Company", "S&P 500"),
            new InstrumentRef("SOLV", "Solventum", "S&P 500"),
            new InstrumentRef("SPG", "Simon Property Group", "S&P 500"),
            new InstrumentRef("SPGI", "S&P Global", "S&P 500"),
            new InstrumentRef("SRE", "Sempra", "S&P 500"),
            new InstrumentRef("STE", "Steris", "S&P 500"),
            new InstrumentRef("STLD", "Steel Dynamics", "S&P 500"),
            new InstrumentRef("STT", "State Street Corporation", "S&P 500"),
            new InstrumentRef("STX", "Seagate Technology", "S&P 500"),
            new InstrumentRef("STZ", "Constellation Brands", "S&P 500"),
            new InstrumentRef("SW", "Smurfit Westrock", "S&P 500"),
            new InstrumentRef("SWK", "Stanley Black & Decker", "S&P 500"),
            new InstrumentRef("SWKS", "Skyworks Solutions", "S&P 500"),
            new InstrumentRef("SYF", "Synchrony Financial", "S&P 500"),
            new InstrumentRef("SYK", "Stryker Corporation", "S&P 500"),
            new InstrumentRef("SYY", "Sysco", "S&P 500"),
            new InstrumentRef("T", "AT&T", "S&P 500"),
            new InstrumentRef("TDG", "TransDigm Group", "S&P 500"),
            new InstrumentRef("TDY", "Teledyne Technologies", "S&P 500"),
            new InstrumentRef("TECH", "Bio-Techne", "S&P 500"),
            new InstrumentRef("TEL", "TE Connectivity", "S&P 500"),
            new InstrumentRef("TER", "Teradyne", "S&P 500"),
            new InstrumentRef("TFC", "Truist Financial", "S&P 500"),
            new InstrumentRef("TGT", "Target Corporation", "S&P 500"),
            new InstrumentRef("TJX", "TJX Companies", "S&P 500"),
            new InstrumentRef("TKO", "TKO Group Holdings", "S&P 500"),
            new InstrumentRef("TMO", "Thermo Fisher Scientific", "S&P 500"),
            new InstrumentRef("TMUS", "T-Mobile US", "S&P 500"),
            new InstrumentRef("TPL", "Texas Pacific Land Corporation", "S&P 500"),
            new InstrumentRef("TPR", "Tapestry, Inc.", "S&P 500"),
            new InstrumentRef("TRGP", "Targa Resources", "S&P 500"),
            new InstrumentRef("TRMB", "Trimble Inc.", "S&P 500"),
            new InstrumentRef("TROW", "T. Rowe Price", "S&P 500"),
            new InstrumentRef("TRV", "Travelers Companies (The)", "S&P 500"),
            new InstrumentRef("TSCO", "Tractor Supply", "S&P 500"),
            new InstrumentRef("TSLA", "Tesla, Inc.", "S&P 500"),
            new InstrumentRef("TSN", "Tyson Foods", "S&P 500"),
            new InstrumentRef("TT", "Trane Technologies", "S&P 500"),
            new InstrumentRef("TTWO", "Take-Two Interactive", "S&P 500"),
            new InstrumentRef("TXN", "Texas Instruments", "S&P 500"),
            new InstrumentRef("TXT", "Textron", "S&P 500"),
            new InstrumentRef("TYL", "Tyler Technologies", "S&P 500"),
            new InstrumentRef("UAL", "United Airlines Holdings", "S&P 500"),
            new InstrumentRef("UBER", "Uber", "S&P 500"),
            new InstrumentRef("UDR", "UDR, Inc.", "S&P 500"),
            new InstrumentRef("UHS", "Universal Health Services", "S&P 500"),
            new InstrumentRef("ULTA", "Ulta Beauty", "S&P 500"),
            new InstrumentRef("UNH", "UnitedHealth Group", "S&P 500"),
            new InstrumentRef("UNP", "Union Pacific Corporation", "S&P 500"),
            new InstrumentRef("UPS", "United Parcel Service", "S&P 500"),
            new InstrumentRef("URI", "United Rentals", "S&P 500"),
            new InstrumentRef("USB", "U.S. Bancorp", "S&P 500"),
            new InstrumentRef("V", "Visa Inc.", "S&P 500"),
            new InstrumentRef("VEEV", "Veeva Systems", "S&P 500"),
            new InstrumentRef("VICI", "Vici Properties", "S&P 500"),
            new InstrumentRef("VLO", "Valero Energy", "S&P 500"),
            new InstrumentRef("VLTO", "Veralto", "S&P 500"),
            new InstrumentRef("VMC", "Vulcan Materials Company", "S&P 500"),
            new InstrumentRef("VMRK", "Vivmark Residential", "S&P 500"),
            new InstrumentRef("VRSK", "Verisk Analytics", "S&P 500"),
            new InstrumentRef("VRSN", "Verisign", "S&P 500"),
            new InstrumentRef("VRT", "Vertiv", "S&P 500"),
            new InstrumentRef("VRTX", "Vertex Pharmaceuticals", "S&P 500"),
            new InstrumentRef("VST", "Vistra Corp.", "S&P 500"),
            new InstrumentRef("VTR", "Ventas", "S&P 500"),
            new InstrumentRef("VTRS", "Viatris", "S&P 500"),
            new InstrumentRef("VZ", "Verizon", "S&P 500"),
            new InstrumentRef("WAB", "Wabtec", "S&P 500"),
            new InstrumentRef("WAT", "Waters Corporation", "S&P 500"),
            new InstrumentRef("WBD", "Warner Bros. Discovery", "S&P 500"),
            new InstrumentRef("WDAY", "Workday, Inc.", "S&P 500"),
            new InstrumentRef("WDC", "Western Digital", "S&P 500"),
            new InstrumentRef("WEC", "WEC Energy Group", "S&P 500"),
            new InstrumentRef("WELL", "Welltower", "S&P 500"),
            new InstrumentRef("WFC", "Wells Fargo", "S&P 500"),
            new InstrumentRef("WM", "Waste Management", "S&P 500"),
            new InstrumentRef("WMB", "Williams Companies", "S&P 500"),
            new InstrumentRef("WMT", "Walmart", "S&P 500"),
            new InstrumentRef("WRB", "W. R. Berkley Corporation", "S&P 500"),
            new InstrumentRef("WSM", "Williams-Sonoma, Inc.", "S&P 500"),
            new InstrumentRef("WST", "West Pharmaceutical Services", "S&P 500"),
            new InstrumentRef("WTW", "Willis Towers Watson", "S&P 500"),
            new InstrumentRef("WY", "Weyerhaeuser", "S&P 500"),
            new InstrumentRef("WYNN", "Wynn Resorts", "S&P 500"),
            new InstrumentRef("XEL", "Xcel Energy", "S&P 500"),
            new InstrumentRef("XOM", "ExxonMobil", "S&P 500"),
            new InstrumentRef("XYL", "Xylem Inc.", "S&P 500"),
            new InstrumentRef("XYZ", "Block, Inc.", "S&P 500"),
            new InstrumentRef("YUM", "Yum! Brands", "S&P 500"),
            new InstrumentRef("ZBH", "Zimmer Biomet", "S&P 500"),
            new InstrumentRef("ZBRA", "Zebra Technologies", "S&P 500"),
            new InstrumentRef("ZTS", "Zoetis", "S&P 500")
    );
}
